import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Configure Google Font
const inter = Inter({ subsets: ["latin"] });

// Define Metadata for the application
export const metadata: Metadata = {
  title: "Create Next App", description: "Generated by create next app"};

// Root Layout Component
export default function RootLayout({
  children}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
